## Python Introduction II:
### 1. Lambda Functions
### 2. Reading files
### 3. NumPy 
### 4. Extra reading

## 1. Lambda Functions

### 1.1 Overview

### Lambda functions (also called anonymous functions) are one line functions that have no name and only have one expression as their body.
#### In Python they are defined using the lambda keyword:



`lambda num : num * 2`

In the example above, the expression is composed of:

* The keyword: lambda
* A variable: num
* A body: num * 2

Because a lambda function is an expression, it can be named. Therefore you could write the previous code as follows:

In [1]:
add_one = lambda x: x + 1
add_one(2)
3

3

The above lambda function is equivalent to writing this:

In [2]:
def add_one(x):
    
    return x + 1

Lambda functions can accept more arguments:

`lambda a, b : a * b`

In [3]:
# and invoking the function:
multiply = lambda a, b : a * b

print(multiply(12, 2)) 

24


### 1.2 Map function

Python’s map() is a built-in function that allows you to process and transform all the items in an iterable without using an explicit for loop, a technique commonly known as mapping. 
map() is useful when you need to apply a transformation function to each item in an iterable and transform them into a new iterable.

In [4]:
# Example using a function to square a number
def square(number):
    return number ** 2

numbers = [1, 2, 3, 4, 5]

In [5]:
squared = map(square, numbers)

list(squared)
[1, 4, 9, 16, 25]

[1, 4, 9, 16, 25]

In [6]:
# same as the for loop:
list_sq = []
for num in numbers:
    list_sq.append(square(num))
    
print(list_sq)

[1, 4, 9, 16, 25]


In [7]:
## same as the list comprehension:
[square(num) for num in numbers]

[1, 4, 9, 16, 25]

In [8]:
# Example for converting str to int:
str_nums = ["4", "8", "6", "5", "3", "2", "8", "9", "2", "5"]

In [9]:
int_nums = map(int, str_nums)

In [10]:
int_nums

In [11]:
list(int_nums)

[4, 8, 6, 5, 3, 2, 8, 9, 2, 5]

In [12]:
# you can also use different kinds of functions
numbers = [-2, -1, 0, 1, 2]

In [13]:
abs_values = list(map(abs, numbers))

In [14]:
abs_values

[2, 1, 0, 1, 2]

In [15]:
list(map(float, numbers))

[-2.0, -1.0, 0.0, 1.0, 2.0]

In [16]:
words = ["Perro", "Gato", "Hamster"]

In [17]:
list(map(len, words))

[5, 4, 7]

In [18]:
# Processing Multiple Input Iterables With map()

In [19]:
first_it = [1, 2, 3]

In [20]:
second_it = [2, 3, 4, 5]

In [21]:
list(map(pow, first_it, second_it))

[1, 8, 81]

The final iterable is only as long as the shortest iterable, which is first_it in this case.

## 2. Reading Files

You can read a file with the open() built-in function. This function uses the path of the file as the argument and returns a file object:

In [22]:
file = open('read_file.txt')

In [23]:
file

<_io.TextIOWrapper name='read_file.txt' mode='r' encoding='UTF-8'>

In [24]:
file.closed

False

Then you should close the file

In [25]:
file.close()

In [26]:
file.closed

True

Another way to open a file is using a context manager:

In [27]:
# This automatically closes the file
with open('read_file.txt') as reader:
    # Further file processing goes here
    pass

In [28]:
file.closed

True

There is a second argument in the open function that specifes the mode (Reading, writing, binary, etc)


* `r` Open for reading (default)
* `w` Open for writing, truncating (overwriting) the file first
* `rb` or `wb` Open in binary mode (read/write using byte data)

`file = open('read_file.txt')` same as `file = open('read_file.txt', 'r')`

You can read about all the modes in the docs https://docs.python.org/3/library/functions.html#open

There are multiple methods that can be called on a file object to help you out:

|Method | What it does | 
|:-------:|:--------------:|
|.read(size=-1) | This reads from the file based on the number of size bytes. If no argument is passed or None or -1 is passed, then the entire file is read. |
|.readline(size=-1) | This reads at most size number of characters from the line. This continues to the end of the line and then wraps back around. If no argument is passed or None or -1 is passed, then the entire line (or rest of the line) is read. |
| .readlines() | This reads the remaining lines from the file object and returns them as a list. |

Example of how to open and read the entire file using .read():

In [29]:
with open('read_file.txt', 'r') as reader:
    # Read & print the entire file
    print(reader.read())

Markdown is a great tool for documentation on Github
because documentation is only as useful as it is readable.
Among other things, Github's flavor of markdown allows for the creation
of tables to display data in rows and columns.



Example of how to read 5 bytes of a line each time using the Python .readline() method:

In [30]:
with open('read_file.txt', 'r') as reader:
    # Read & print the first 8 characters of the line 5 times
    print(reader.readline(8))
    print(reader.readline(8))
    print(reader.readline(8))
    print(reader.readline(8))
    print(reader.readline(8))

Markdown
 is a gr
eat tool
 for doc
umentati


Example of how to read the entire file as a list using the Python .readlines() method:

In [31]:
f = open('read_file.txt')

In [32]:
f.readlines()  # Returns a list object

['Markdown is a great tool for documentation on Github\n',
 'because documentation is only as useful as it is readable.\n',
 "Among other things, Github's flavor of markdown allows for the creation\n",
 'of tables to display data in rows and columns.\n']

In [33]:
# Notice the symbol '\n' that means end of line

A way you could iterate over each line in the file is to use the Python .readlines() method of the file object. .readlines() returns a list where each element in the list represents a line in the file:

In [34]:
with open('read_file.txt', 'r') as reader:
    for line in reader.readlines():
        print(line)

Markdown is a great tool for documentation on Github

because documentation is only as useful as it is readable.

Among other things, Github's flavor of markdown allows for the creation

of tables to display data in rows and columns.



## 3. NumPy 

First we need to import the numpy library:

In [35]:
import numpy as np

### 3.1 Arrays

* A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.

* The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

* We can initialize numpy arrays from nested Python lists, and access elements using square brackets:


In [36]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)          

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [37]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [38]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [39]:
#Numpy also provides many functions to create arrays:

a = np.zeros((2,2))  # Create an array of all zeros
print(a)

b = np.ones((1,2))   # Create an array of all ones
print(b)

c = np.full((2,2), 7) # Create a constant array
print(c)

d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.24589828 0.86666093]
 [0.42364196 0.40822064]]


### 3.2 Array indexing

Since arrays may be multidimensional, you must specify a slice for each dimension of the array:


In [40]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [41]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [42]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])

2
77


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array:

In [43]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [44]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
print(row_r1, row_r1.shape)

[5 6 7 8] (4,)


In [45]:
#Using only slices yields an array of the same rank as the
#original array:
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [46]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


Integer array indexing allows you to construct arbitrary arrays using the data from another array. For example:

In [47]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [48]:
# Example of integer array indexing.
print(a[[0, 1, 2], [0, 1, 0]])

[1 4 5]


In [49]:
# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]


In [50]:
# Repeating an the element corresponding to a[0,1]:
print(a[[0, 0], [1, 1]])


[2 2]


It is also possible to mutate elements of an array:

In [51]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [52]:
a[2,2] += 10

In [53]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 19],
       [10, 11, 12]])

Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:


In [54]:

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [55]:
bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.


In [56]:
print(bool_idx)


[[False False]
 [ True  True]
 [ True  True]]


In [57]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

[3 4 5 6]


In [58]:
# We can do all of the above in a single concise statement:
print(a[a > 2])


[3 4 5 6]


### 3.3 Data types

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:


In [59]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


### 3.4 Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:


In [60]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [61]:
# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [62]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [63]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [64]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [65]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that, `*` is elementwise multiplication, not matrix multiplication as in other languages like MATLAB. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:


In [66]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [67]:
v = np.array([9,10])
w = np.array([11, 12])

In [68]:
# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


You can also use the `@` operator which is equivalent to numpy's `dot` operator.

In [69]:
print(v @ w)


219


In [70]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[29 67]
[29 67]
[29 67]


In [71]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:


In [72]:
x = np.array([[1,2],[3,4]])

In [73]:
print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the [documentation](https://numpy.org/doc/stable/reference/routines.math.html).


Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [74]:
print(x)
print("transpose\n", x.T)

[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]


In [75]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


## 4. Extra reading

### 4.1 Filter function

#### Suggested reading: https://realpython.com/python-filter-function/

### 4.2 Numpy Broadcasting

#### Suggested reading https://www.geeksforgeeks.org/python-broadcasting-with-numpy-arrays/

### 4.3 SQL connection to database

#### Suggested reading https://www.postgresqltutorial.com/postgresql-python/connect/

## 5. References

* https://realpython.com/python-lambda/
* https://realpython.com/python-map-function/
* https://realpython.com/read-write-files-python/
* https://colab.research.google.com/github/cs231n/cs231n.github.io/blob/master/python-colab.ipynb#scrollTo=kiMDUr58L9hN